# permissions for end users to edit lvmclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lvmcluster-editor-role
rules:
- apiGroups:
  - storage.storage.domain
  resources:
  - lvmclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.storage.domain
  resources:
  - lvmclusters/status
  verbs:
  - get
